name: Dummy Run

on:
  workflow_dispatch:
  #push:
  #  branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: fastapi-ecr-repo-20250718

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env vars from config.ini using Python
        run: python3 configs/load_config.py

      - name: Use the environment variables
        run: |
          echo "VPC_NAME: $VPC_NAME"
          echo "ECR_REPO_NAME: $ECR_REPO_NAME"

      - name: print the env
        run: env